### ISSUE TITLE
PShape (.obj and .mtl) materials ignored in Android Mode

### ISSUE THREAD

**Issue by darkwave** [processing/processing-android-archive#43]
If I use a .obj file with a .mtl and NO texture (uv map) all models materials are ignored and a transparent light-blue material is used instead.

Example loadDisplayOBJ works fine because it has a uvmap texture. Try some models with no texture and you'll see! ;-)

**Comment by boubpopsyteam** [comment]
I've tested with an obj with no mtl and no texture => I confirm

@codeanticode wasn't this fixed already ? ( https://github.com/processing/processing/issues/1667 )

**Comment by darkwave** [comment]
This bug still persists in 2.0.1 version of Processing. I'm testing using Android Emulator running with 3D acceleration enabled and with Processing 2.0b7 it works fine both for textures and materials.

Note: I made a "fresh installation" removing .android and .processing and sketchbook folders. And installed Android mode via IDE.

**Comment by codeanticode** [comment]
hi, this issue hasn't been fixed yet (on android) because the android build of core is based on an older source, before the 2.0 release.

**Comment by codeanticode** [comment]
the opengl renderer was updated to the latest version from the desktop mode (https://github.com/processing/processing-android/commit/411bb20066b651a9c4437b78e7cbc3bafb662afa), which should solve this kind of issues.

**Comment by darkwave** [comment]
I think this issue is still there and actually it was never fixed :-(
